import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import QueryProvider from "./components/queryProvider";
import LateralMenu from "./components/lateralMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <div className="flex">
            <div className="h-[100vh]">
              <LateralMenu />
            </div>
            <div className="w-full">
              <Navbar />
              <div className="container mx-auto pt-12 px-5">{children}</div>
            </div>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
